store-file = "./wow-db.txt"

[server]
address = ":8080"
bit-strength = 24
secret-key = "GLx%y@~z5mR6V3p6"
timeout = "10s"
expiration = "4m"
rate-limit = 10

[cache]
expiration = "4m"

[cache-redis]
host = "redis"
port = 6379
password = ""
db = 0
pool-size = 100